<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SQLBI.Whiteboard.Core\SQLBI.Whiteboard.Core.csproj" />
    <ProjectReference Include="..\..\src\SQLBI.Whiteboard.Dax\SQLBI.Whiteboard.Dax.csproj" />
    <ProjectReference Include="..\..\src\SQLBI.Whiteboard.SqlServer\SQLBI.Whiteboard.SqlServer.csproj" />
  </ItemGroup>
</Project>
