<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWPF>true</UseWPF>
    <AssemblyName>SQLBI.Whiteboard</AssemblyName>
    <RootNamespace>SQLBI.Whiteboard</RootNamespace>
    <AssemblyTitle>SQLBI Whiteboard</AssemblyTitle>
    <Product>SQLBI Whiteboard</Product>
    <ApplicationIcon>Assets\SQLBI.Whiteboard.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\SQLBI.Whiteboard.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SQLBI.Whiteboard.Core\SQLBI.Whiteboard.Core.csproj" />
    <ProjectReference Include="..\SQLBI.Whiteboard.Dax\SQLBI.Whiteboard.Dax.csproj" />
    <ProjectReference Include="..\SQLBI.Whiteboard.SqlServer\SQLBI.Whiteboard.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Vortice.Wpf" Version="3.8.3" />
  </ItemGroup>
</Project>
