<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>SQLBI.Whiteboard</AssemblyName>
    <RootNamespace>SQLBI.Whiteboard</RootNamespace>
    <AssemblyTitle>SQLBI Whiteboard</AssemblyTitle>
    <Product>SQLBI Whiteboard</Product>
    <ApplicationIcon>Assets\SQLBI.Whiteboard.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\SQLBI.Whiteboard.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SQLBI.Whiteboard.Core\SQLBI.Whiteboard.Core.csproj" />
  </ItemGroup>
</Project>
