// Generated from the DAX Formatter reference grammar (daxformatter/DaxFormatter/DaxGrammar.cs).
// These are the names the formatter is allowed to normalize to upper case. Any identifier that
// is not in this set keeps the casing the author wrote, so a variable named "Year" stays "Year".

namespace SQLBI.Whiteboard.Dax.Engine;

internal static class DaxFunctions
{
    private const string Names =
        "ABS ACCRINT ACCRINTM ACOS ACOSH ACOT ACOTH ADDCOLUMNS ADDMISSINGITEMS " +
        "AGGREGATIONRECOMMENDATIONS AI.KPIINSIGHTS AI.KPIINSIGHTSSUMMARY ALL ALLCROSSFILTERED " +
        "ALLEXCEPT ALLNOBLANKROW ALLSELECTED ALLSELECTEDAPPLY ALLSELECTEDREMOVE ALWAYSAPPLY " +
        "AMORDEGRC AMORLINC AND APPROXIMATEDISTINCTCOUNT ASIN ASINH ATAN ATANH AVERAGE AVERAGEA " +
        "AVERAGEX BETA.DIST BETA.INV BITAND BITLSHIFT BITOR BITRSHIFT BITXOR BLANK CALCULATE " +
        "CALCULATETABLE CALENDAR CALENDARAUTO CEILING CHISQ.DIST CHISQ.DIST.RT CHISQ.INV " +
        "CHISQ.INV.RT CLOSINGBALANCEMONTH CLOSINGBALANCEQUARTER CLOSINGBALANCEYEAR COALESCE COLLAPSE " +
        "COLLAPSEALL COLUMNSTATISTICS COMBIN COMBINA COMBINEVALUES CONCATENATE CONCATENATEX " +
        "CONFIDENCE.NORM CONFIDENCE.T CONTAINS CONTAINSROW CONTAINSSTRING CONTAINSSTRINGEXACT " +
        "CONVERT COS COSH COT COTH COUNT COUNTA COUNTAX COUNTBLANK COUNTROWS COUNTX COUPDAYBS " +
        "COUPDAYS COUPDAYSNC COUPNCD COUPNUM COUPPCD CROSSFILTER CROSSJOIN CUMIPMT CUMPRINC CURRENCY " +
        "CURRENTGROUP CUSTOMDATA DATATABLE DATE DATEADD DATEDIFF DATESBETWEEN DATESINPERIOD DATESMTD " +
        "DATESQTD DATESYTD DATEVALUE DAY DB DDB DEGREES DEPENDON DETAILROWS DISC DISTINCT " +
        "DISTINCTCOUNT DISTINCTCOUNTNOBLANK DIVIDE DOLLARDE DOLLARFR DURATION EARLIER EARLIEST EDATE " +
        "EFFECT ENDOFMONTH ENDOFQUARTER ENDOFYEAR EOMONTH ERROR EVALUATEANDLOG EVEN EXACT EXCEPT EXP " +
        "EXPAND EXPANDALL EXPON.DIST EXTERNALEXPRESSION EXTERNALMEASURE FACT FALSE FILTER " +
        "FILTERCLUSTER FILTERS FIND FIRST FIRSTDATE FIRSTNONBLANK FIRSTNONBLANKVALUE FIXED FLOOR " +
        "FORMAT FV GCD GENERATE GENERATEALL GENERATESERIES GEOMEAN GEOMEANX GETIMAGE GROUPBY " +
        "GROUPCROSSAPPLY GROUPCROSSAPPLYTABLE HASH HASONEFILTER HASONEVALUE HOUR IF IF.EAGER IFERROR " +
        "IGNORE INDEX INFO.ALTERNATEOFDEFINITIONS INFO.ANNOTATIONS INFO.ATTRIBUTEHIERARCHIES " +
        "INFO.ATTRIBUTEHIERARCHYSTORAGES INFO.CALCULATIONGROUPS INFO.CALCULATIONITEMS INFO.CATALOGS " +
        "INFO.CHANGEDPROPERTIES INFO.COLUMNPARTITIONSTORAGES INFO.COLUMNPERMISSIONS INFO.COLUMNS " +
        "INFO.COLUMNSTORAGES INFO.CULTURES INFO.DATACOVERAGEDEFINITIONS INFO.DATASOURCES " +
        "INFO.DELTATABLEMETADATASTORAGES INFO.DETAILROWSDEFINITIONS INFO.DICTIONARYSTORAGES " +
        "INFO.EXCLUDEDARTIFACTS INFO.EXPRESSIONS INFO.EXTENDEDPROPERTIES " +
        "INFO.FORMATSTRINGDEFINITIONS INFO.FUNCTIONS INFO.GENERALSEGMENTMAPSEGMENTMETADATASTORAGES " +
        "INFO.GROUPBYCOLUMNS INFO.HIERARCHIES INFO.HIERARCHYSTORAGES INFO.INFO_CALCDEPENDENCY " +
        "INFO.KPIS INFO.LEVELS INFO.LINGUISTICMETADATA INFO.MEASURES INFO.MODEL " +
        "INFO.OBJECTTRANSLATIONS INFO.PARQUETFILESTORAGES INFO.PARTITIONS INFO.PARTITIONSTORAGES " +
        "INFO.PERSPECTIVECOLUMNS INFO.PERSPECTIVEHIERARCHIES INFO.PERSPECTIVEMEASURES " +
        "INFO.PERSPECTIVES INFO.PERSPECTIVETABLES INFO.PROPERTIES INFO.QUERYGROUPS " +
        "INFO.REFRESHPOLICIES INFO.RELATEDCOLUMNDETAILS INFO.RELATIONSHIPINDEXSTORAGES " +
        "INFO.RELATIONSHIPS INFO.RELATIONSHIPSTORAGES INFO.ROLEMEMBERSHIPS INFO.ROLES " +
        "INFO.SEGMENTMAPSTORAGES INFO.SEGMENTSTORAGES INFO.STORAGEFILES INFO.STORAGEFOLDERS " +
        "INFO.STORAGETABLECOLUMNS INFO.STORAGETABLECOLUMNSEGMENTS INFO.STORAGETABLES " +
        "INFO.TABLEPERMISSIONS INFO.TABLES INFO.TABLESTORAGES INFO.VARIATIONS INT INTERSECT INTRATE " +
        "IPMT ISAFTER ISATLEVEL ISBLANK ISCROSSFILTERED ISEMPTY ISERROR ISEVEN ISFILTERED ISINSCOPE " +
        "ISLOGICAL ISNONTEXT ISNUMBER ISO.CEILING ISODD ISONORAFTER ISPMT ISSELECTEDMEASURE " +
        "ISSUBTOTAL ISTEXT KEEPFILTERS KEYWORDMATCH LAST LASTDATE LASTNONBLANK LASTNONBLANKVALUE LCM " +
        "LEFT LEN LINEST LINESTX LN LOG LOG10 LOOKUP LOOKUPDECISIONTABLE LOOKUPVALUE LOWER MATCHBY " +
        "MAX MAXA MAXX MDURATION MEDIAN MEDIANX MID MIN MINA MINUTE MINX MOD MONTH MOVINGAVERAGE " +
        "MROUND NAMEOF NATURALINNERJOIN NATURALLEFTOUTERJOIN NETWORKDAYS NEXT NEXTDAY NEXTMONTH " +
        "NEXTQUARTER NEXTYEAR NOMINAL NONFILTER NONVISUAL NORM.DIST NORM.INV NORM.S.DIST NORM.S.INV " +
        "NOT NOW NPER ODD ODDFPRICE ODDFYIELD ODDLPRICE ODDLYIELD OFFSET OPENINGBALANCEMONTH " +
        "OPENINGBALANCEQUARTER OPENINGBALANCEYEAR OR ORDERBY PARALLELPERIOD PARTITIONBY PATH " +
        "PATHCONTAINS PATHITEM PATHITEMREVERSE PATHLENGTH PDURATION PERCENTILE.EXC PERCENTILE.INC " +
        "PERCENTILEX.EXC PERCENTILEX.INC PERMUT PI PMT POISSON.DIST POWER PPMT PREVIOUS PREVIOUSDAY " +
        "PREVIOUSMONTH PREVIOUSQUARTER PREVIOUSYEAR PRICE PRICEDISC PRICEMAT PRODUCT PRODUCTX PV " +
        "QUARTER QUOTIENT RADIANS RAND RANDBETWEEN RANGE RANK RANK.EQ RANKX RATE RECEIVED RELATED " +
        "RELATEDTABLE REMOVEFILTERS REPLACE REPT RIGHT ROLLUP ROLLUPADDISSUBTOTAL ROLLUPGROUP " +
        "ROLLUPISSUBTOTAL ROUND ROUNDDOWN ROUNDUP ROW ROWNUMBER RRI RSCUSTOMDAXFILTER RUNNINGSUM " +
        "SAMEPERIODLASTYEAR SAMPLE SAMPLEAXISWITHLOCALMINMAX SAMPLECARTESIANPOINTSBYCOVER SEARCH " +
        "SECOND SELECTCOLUMNS SELECTEDMEASURE SELECTEDMEASUREFORMATSTRING SELECTEDMEASURENAME " +
        "SELECTEDVALUE SHADOWCLUSTER SIGN SIN SINH SLN SQRT SQRTPI STARTOFMONTH STARTOFQUARTER " +
        "STARTOFYEAR STDEV.P STDEV.S STDEVX.P STDEVX.S SUBSTITUTE SUBSTITUTEWITHINDEX SUM SUMMARIZE " +
        "SUMMARIZECOLUMNS SUMMARIZECOLUMNSAS SUMMARIZECOLUMNSTABLEAS SUMX SWITCH SYD T.DIST " +
        "T.DIST.2T T.DIST.RT T.INV T.INV.2T TAN TANH TBILLEQ TBILLPRICE TBILLYIELD TEMPORALSEMIJOIN " +
        "TIME TIMEVALUE TOCSV TODAY TOJSON TOPN TOPNPERLEVEL TOPNSKIP TOTALMTD TOTALQTD TOTALYTD " +
        "TREATAS TRIM TRUE TRUNC UNICHAR UNICODE UNION UNIONVARIANT UPPER USERCULTURE " +
        "USERELATIONSHIP USERNAME USEROBJECTID USERPRINCIPALNAME UTCNOW UTCTODAY VALUE VALUES VAR.P " +
        "VAR.S VARX.P VARX.S VDB WEEKDAY WEEKNUM WINDOW XIRR XNPV YEAR YEARFRAC YIELD YIELDDISC " +
        "YIELDMAT";

    private static readonly HashSet<string> Known =
        Names.Split(' ', StringSplitOptions.RemoveEmptyEntries).ToHashSet(StringComparer.OrdinalIgnoreCase);

    /// <summary>The canonical upper-case spelling of a known DAX function, or null when unknown.</summary>
    public static string? Canonical(string name) =>
        Known.TryGetValue(name, out var canonical) ? canonical : null;
}
